### ISSUE TITLE
[Bug] LINE_STRIP draws triangle instead.

### ISSUE THREAD

**Issue by IridescentRose** [masterfeizz/picaGL#3]
![image](https://user-images.githubusercontent.com/12397073/204689418-85f7beca-66cb-4b8c-a511-14f40474c26b.png)

This border is drawn with GL_LINE_STRIP in code and still draws as a triangle which looks completely incorrect in this context.

**Comment by Firepal** [comment]
I am not familiar with the pgl code, but having taken a quick look, all the code for rendering GL_LINES is stubbed == not implemented.

This would probably be due to the fact that the 3DS graphics hardware [doesn't implement line rendering.](https://www.3dbrew.org/wiki/GPU/Internal_Registers#GPUREG_PRIMITIVE_CONFIG) (It's even kind of nuts, as the hardware was advertised as "OpenGL 1.1 compatible")

I think it is possible to reimplement lines using custom vertex shader code magic inside pgl...

**Comment by IridescentRose** [comment]
I'll close this because it's not a super big deal.
